//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpCooking.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpCooking.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutView_Title {
            get {
                return ResourceManager.GetString("AboutView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddRecipe {
            get {
                return ResourceManager.GetString("AddRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Recipes.
        /// </summary>
        public static string AllRecipes {
            get {
                return ResourceManager.GetString("AllRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal cooking app..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp Cooking.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AppShell_About {
            get {
                return ResourceManager.GetString("AppShell_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string AppShell_Recipes {
            get {
                return ResourceManager.GetString("AppShell_Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AppShell_Settings {
            get {
                return ResourceManager.GetString("AppShell_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupSetupView_Title {
            get {
                return ResourceManager.GetString("BackupSetupView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelEditRecipe {
            get {
                return ResourceManager.GetString("CancelEditRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropbox.
        /// </summary>
        public static string DropBoxProviderName {
            get {
                return ResourceManager.GetString("DropBoxProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse recipe id.
        /// </summary>
        public static string EditItemView_FailedToParse {
            get {
                return ResourceManager.GetString("EditItemView_FailedToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string EditItemView_Ingredients {
            get {
                return ResourceManager.GetString("EditItemView_Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string EditItemView_Instructions {
            get {
                return ResourceManager.GetString("EditItemView_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string EditItemView_Notes {
            get {
                return ResourceManager.GetString("EditItemView_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditItemView_PickImageCancel {
            get {
                return ResourceManager.GetString("EditItemView_PickImageCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from library.
        /// </summary>
        public static string EditItemView_PickImagePickImage {
            get {
                return ResourceManager.GetString("EditItemView_PickImagePickImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is your image?.
        /// </summary>
        public static string EditItemView_PickImageTitle {
            get {
                return ResourceManager.GetString("EditItemView_PickImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Camera.
        /// </summary>
        public static string EditItemView_PickImageUseCamera {
            get {
                return ResourceManager.GetString("EditItemView_PickImageUseCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EditItemView_Save {
            get {
                return ResourceManager.GetString("EditItemView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string EditItemView_Source {
            get {
                return ResourceManager.GetString("EditItemView_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string EditItemView_Title {
            get {
                return ResourceManager.GetString("EditItemView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Recipe.
        /// </summary>
        public static string EditRecipe {
            get {
                return ResourceManager.GetString("EditRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ErrorOk {
            get {
                return ResourceManager.GetString("ErrorOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string FavoriteRecipe {
            get {
                return ResourceManager.GetString("FavoriteRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?&lt;Fraction&gt;\d+\/\d+)|^(?&lt;Regular&gt;\d+\.{0,1}\d*).
        /// </summary>
        public static string IngredientQuantityRegex {
            get {
                return ResourceManager.GetString("IngredientQuantityRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string ItemDetailView_DayAbbreviation {
            get {
                return ResourceManager.GetString("ItemDetailView_DayAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy!.
        /// </summary>
        public static string ItemDetailView_Enjoy {
            get {
                return ResourceManager.GetString("ItemDetailView_Enjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse input id.
        /// </summary>
        public static string ItemDetailView_FailedToParseInputId {
            get {
                return ResourceManager.GetString("ItemDetailView_FailedToParseInputId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string ItemDetailView_Ingredients {
            get {
                return ResourceManager.GetString("ItemDetailView_Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ItemDetailView_MoreCancel {
            get {
                return ResourceManager.GetString("ItemDetailView_MoreCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ItemDetailView_MoreDelete {
            get {
                return ResourceManager.GetString("ItemDetailView_MoreDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? This is not reversible..
        /// </summary>
        public static string ItemDetailView_MoreDeleteConfirmation {
            get {
                return ResourceManager.GetString("ItemDetailView_MoreDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ItemDetailView_MoreDeleteNo {
            get {
                return ResourceManager.GetString("ItemDetailView_MoreDeleteNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ItemDetailView_MoreDeleteYes {
            get {
                return ResourceManager.GetString("ItemDetailView_MoreDeleteYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ItemDetailView_MoreTitle {
            get {
                return ResourceManager.GetString("ItemDetailView_MoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ItemDetailView_MultiplierCancel {
            get {
                return ResourceManager.GetString("ItemDetailView_MultiplierCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter decimal value of quantity. E.g. 0.5 or 2.
        /// </summary>
        public static string ItemDetailView_MultiplierDescription {
            get {
                return ResourceManager.GetString("ItemDetailView_MultiplierDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ItemDetailView_MultiplierOk {
            get {
                return ResourceManager.GetString("ItemDetailView_MultiplierOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier.
        /// </summary>
        public static string ItemDetailView_MultiplierTitle {
            get {
                return ResourceManager.GetString("ItemDetailView_MultiplierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string ItemDetailView_Notes {
            get {
                return ResourceManager.GetString("ItemDetailView_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe deleted.
        /// </summary>
        public static string ItemDetailView_RecipeDeleted {
            get {
                return ResourceManager.GetString("ItemDetailView_RecipeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Recipe.
        /// </summary>
        public static string ItemDetailView_Share {
            get {
                return ResourceManager.GetString("ItemDetailView_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ItemDetailView_StartTimeCancel {
            get {
                return ResourceManager.GetString("ItemDetailView_StartTimeCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ItemDetailView_StartTimeOk {
            get {
                return ResourceManager.GetString("ItemDetailView_StartTimeOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string ItemDetailView_StartTimeTitle {
            get {
                return ResourceManager.GetString("ItemDetailView_StartTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string ItemDetailView_Step {
            get {
                return ResourceManager.GetString("ItemDetailView_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search term.
        /// </summary>
        public static string ItemsView_EnterSearchTerm {
            get {
                return ResourceManager.GetString("ItemsView_EnterSearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to show. How about you create some yummy recipes?.
        /// </summary>
        public static string ItemsView_NothingToShow {
            get {
                return ResourceManager.GetString("ItemsView_NothingToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search items....
        /// </summary>
        public static string ItemsView_SearchItems {
            get {
                return ResourceManager.GetString("ItemsView_SearchItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string MultiplierQuantityAggregator {
            get {
                return ResourceManager.GetString("MultiplierQuantityAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Recipe.
        /// </summary>
        public static string NewRecipe {
            get {
                return ResourceManager.GetString("NewRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string SelectCultureView_Title {
            get {
                return ResourceManager.GetString("SelectCultureView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up to.
        /// </summary>
        public static string SettingsView_BackingUpTo {
            get {
                return ResourceManager.GetString("SettingsView_BackingUpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string SettingsView_Backup {
            get {
                return ResourceManager.GetString("SettingsView_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humm... That file looks weird. Are you sure it is a Sharp Cooking backup file?.
        /// </summary>
        public static string SettingsView_BadBackupFile {
            get {
                return ResourceManager.GetString("SettingsView_BadBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this moment we don&apos;t support selecting the language here, please change the language in your phone..
        /// </summary>
        public static string SettingsView_CannotChangeCulture {
            get {
                return ResourceManager.GetString("SettingsView_CannotChangeCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no! Your backup lookups corrupted and I wasn&apos;t able to restore it..
        /// </summary>
        public static string SettingsView_CorruptedBackupFile {
            get {
                return ResourceManager.GetString("SettingsView_CorruptedBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export a new backup to file.
        /// </summary>
        public static string SettingsView_ExportBackup {
            get {
                return ResourceManager.GetString("SettingsView_ExportBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string SettingsView_Help {
            get {
                return ResourceManager.GetString("SettingsView_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact developer.
        /// </summary>
        public static string SettingsView_HelpContact {
            get {
                return ResourceManager.GetString("SettingsView_HelpContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsView_Language {
            get {
                return ResourceManager.GetString("SettingsView_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier result format.
        /// </summary>
        public static string SettingsView_MultiplierResultFormat {
            get {
                return ResourceManager.GetString("SettingsView_MultiplierResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display decimals like 1.5.
        /// </summary>
        public static string SettingsView_MultiplyResultDisplayUseDecimal {
            get {
                return ResourceManager.GetString("SettingsView_MultiplyResultDisplayUseDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display fractions like 1 and 1/2.
        /// </summary>
        public static string SettingsView_MultiplyResultDisplayUseFractions {
            get {
                return ResourceManager.GetString("SettingsView_MultiplyResultDisplayUseFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weird... There are no recipes in this backup..
        /// </summary>
        public static string SettingsView_NoRecipesToRestore {
            get {
                return ResourceManager.GetString("SettingsView_NoRecipesToRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        public static string SettingsView_NotSupported {
            get {
                return ResourceManager.GetString("SettingsView_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where should we save your backup data?.
        /// </summary>
        public static string SettingsView_PickBackupLocation {
            get {
                return ResourceManager.GetString("SettingsView_PickBackupLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string SettingsView_Privacy {
            get {
                return ResourceManager.GetString("SettingsView_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review our privacy policy.
        /// </summary>
        public static string SettingsView_PrivacyPolicy {
            get {
                return ResourceManager.GetString("SettingsView_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problem. We can do this later..
        /// </summary>
        public static string SettingsView_ResourceCancelledContent {
            get {
                return ResourceManager.GetString("SettingsView_ResourceCancelledContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backup.
        /// </summary>
        public static string SettingsView_RestoreBackup {
            get {
                return ResourceManager.GetString("SettingsView_RestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore an existing backup from file.
        /// </summary>
        public static string SettingsView_RestoreBackupFromFile {
            get {
                return ResourceManager.GetString("SettingsView_RestoreBackupFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string SettingsView_RestoreCancelled {
            get {
                return ResourceManager.GetString("SettingsView_RestoreCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore is done..
        /// </summary>
        public static string SettingsView_RestoreIsDone {
            get {
                return ResourceManager.GetString("SettingsView_RestoreIsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup backup.
        /// </summary>
        public static string SettingsView_SetupBackup {
            get {
                return ResourceManager.GetString("SettingsView_SetupBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps Interval.
        /// </summary>
        public static string SettingsView_StepsInterval {
            get {
                return ResourceManager.GetString("SettingsView_StepsInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsView_StepsIntervalCancel {
            get {
                return ResourceManager.GetString("SettingsView_StepsIntervalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many minutes between not timed steps?.
        /// </summary>
        public static string SettingsView_StepsIntervalDescription {
            get {
                return ResourceManager.GetString("SettingsView_StepsIntervalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string SettingsView_StepsIntervalOk {
            get {
                return ResourceManager.GetString("SettingsView_StepsIntervalOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step interval.
        /// </summary>
        public static string SettingsView_StepsIntervalTitle {
            get {
                return ResourceManager.GetString("SettingsView_StepsIntervalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes when no time information is given.
        /// </summary>
        public static string SettingsView_TimeStepsDescriptoin {
            get {
                return ResourceManager.GetString("SettingsView_TimeStepsDescriptoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;Minutes&gt;\d+\.{0,1}\d*)\s*(minutes|minute|min)\b|(?&lt;Hours&gt;\d+\.{0,1}\d*)\s*(hours|hour)\b|(?&lt;Days&gt;\d+\.{0,1}\d*)\s*(days|day)\b.
        /// </summary>
        public static string StepTimeIdentifierRegex {
            get {
                return ResourceManager.GetString("StepTimeIdentifierRegex", resourceCulture);
            }
        }
    }
}
